sudo: required
services:
  - docker

before_install:
  - docker build -t dheeraj4vv/docker-react -f dockerfile.dev .

script:
  - docker run dheeraj4vv/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-create"
  env: "DockerCreate-env"
  bucket_name: "elasticbeanstalk-us-east-2-990381690977"
  bucket_path: "docker-create"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
